CONF=sun20i
CONFLIST=sun20i

KTZERO=0xFFFFFFFFC1000000	# KZERO+PHYSTEXT, must match mem.h

objtype=riscv64
</$objtype/mkfile
p=9

DEVS=`{rc ../port/mkdevlist $CONF}

PORT=\
	alarm.$O\
	alloc.$O\
	allocb.$O\
	auth.$O\
	cache.$O\
	chan.$O\
	dev.$O\
	edf.$O\
	fault.$O\
	mul64fract.$O\
	page.$O\
	parse.$O\
	pgrp.$O\
	portclock.$O\
	print.$O\
	proc.$O\
	qio.$O\
	qlock.$O\
	segment.$O\
	sysfile.$O\
	sysproc.$O\
	taslock.$O\
	tod.$O\
	xalloc.$O\
	random.$O\
	rdb.$O\
	syscallfmt.$O\

OBJ=\
	l.$O\
	main.$O\
	mmu.$O\
	trap.$O\
	timer.$O\
	plic.$O\
	wdt.$O\
	stub.$O\
	$DEVS\
	$PORT\

LIB=\
	/$objtype/lib/libsec.a\
	/$objtype/lib/libmp.a\
	/$objtype/lib/libc.a\

$p$CONF:D:	$OBJ $CONF.$O $LIB
	$LD $DFLAGS -s -H 1 -T $KTZERO -E _start -l -o $target $prereq

<../port/portmkfile
